// <auto-generated />
namespace MyELearningProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_migration_profile2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_migration_profile2));
        
        string IMigrationMetadata.Id
        {
            get { return "202311301114241_add_migration_profile2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
